// Module-level cache so repeated lookups within a session are instant
const headshotCache = new Map();

// playerIds.json is generated by scripts/generatePlayerIds.js
// Format: { "last, first": mlbId, ... }
let playerIdMap = null;

async function getPlayerIdMap() {
  if (playerIdMap) return playerIdMap;
  try {
    const res = await fetch('/data/playerIds.json');
    playerIdMap = res.ok ? await res.json() : {};
  } catch {
    playerIdMap = {};
  }
  return playerIdMap;
}

/**
 * Converts "last, first" CSV format to "First Last" for display.
 * Preserves accented characters (e.g. "morejón, adrián" -> "Adrián Morejón").
 */
export function formatPlayerName(csvName) {
  if (!csvName) return '';
  const parts = csvName.split(',');
  if (parts.length !== 2) return toTitleCase(csvName);
  return `${toTitleCase(parts[1].trim())} ${toTitleCase(parts[0].trim())}`;
}

function toTitleCase(str) {
  // \b is ASCII-only so accented chars like ó create spurious word boundaries.
  // Lookbehind on ^|\s only capitalizes letters at the start of a word.
  return str.replace(/(?<=^|\s)\p{L}/gu, (c) => c.toUpperCase());
}

/**
 * Returns the MLB headshot CDN URL for a pitcher, or null if not found.
 * Resolution order:
 *   1. Module cache (instant, same session)
 *   2. playerIds.json (generated by scripts/generatePlayerIds.js, bundled at build)
 *   3. Live MLB Stats API call (fallback for players missing from the JSON)
 *
 * @param {string} csvName - "last, first" format from the CSV
 * @returns {Promise<string|null>}
 */
export async function getPlayerHeadshot(csvName) {
  if (headshotCache.has(csvName)) return headshotCache.get(csvName);

  // Try pre-generated map first
  const map = await getPlayerIdMap();
  let mlbId = map[csvName] ?? null;

  // Fall back to live API lookup for players not in the map
  if (!mlbId) {
    mlbId = await lookupMlbId(formatPlayerName(csvName));
  }

  const url = mlbId
    ? `https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_360,q_auto:best/v1/people/${mlbId}/headshot/67/current`
    : null;

  headshotCache.set(csvName, url);
  return url;
}

async function lookupMlbId(displayName) {
  try {
    const res = await fetch(
      `https://statsapi.mlb.com/api/v1/people/search?names=${encodeURIComponent(displayName)}&sportIds=1`
    );
    if (!res.ok) return null;
    const json = await res.json();
    return json.people?.[0]?.id ?? null;
  } catch {
    return null;
  }
}

export function getHeadshotUrl(mlbId) {
  return `https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_180,q_auto:best/v1/people/${mlbId}/headshot/67/current`;
}
